name: Othello API CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Set environment variables
        run: |
          echo 'JwtSettings__Secret="${{ secrets.JWT_SECRET }}"' >> $GITHUB_ENV
          echo 'ConnectionStrings__DefaultConnection="${{ secrets.DB_CONNECTION }}"' >> $GITHUB_ENV
          echo 'EmailSettings__SmtpUsername="${{ secrets.SMTP_USERNAME }}"' >> $GITHUB_ENV
          echo 'EmailSettings__SmtpPassword="${{ secrets.SMTP_PASSWORD }}"' >> $GITHUB_ENV

      - name: Run tests
        run: dotnet test --no-build --configuration Release
